# Generated by Django 5.0.6 on 2024-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
