# Generated by Django 5.0.6 on 2024-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/cover'),
        ),
        migrations.AddField(
            model_name='course',
            name='overview_video',
            field=models.FileField(blank=True, null=True, upload_to='course/overview'),
        ),
    ]
