# Generated by Django 5.0.6 on 2024-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_subject_owner_alter_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/covers'),
        ),
    ]
